### ISSUE TITLE
Node Breaking

### ISSUE THREAD

**Issue by mwo-aec** [alvpickmans/JsonData#5]
Hi, the node **JsonObject.GetValueByKey** when ever I open my dynamo scripts again (the more I save the worst it "breaks"). Image is a few open/saves etc.
![GetValueByKey](https://user-images.githubusercontent.com/54068359/70413630-83e18900-1a60-11ea-956b-36e293a79ed8.png)

My current Revit & Dynamo versions:
![Revit 2020 2](https://user-images.githubusercontent.com/54068359/70413652-8f34b480-1a60-11ea-8254-3cbdf2a0fcb1.png)
![Dynamo 2 3](https://user-images.githubusercontent.com/54068359/70413653-8f34b480-1a60-11ea-83c4-c18aef63dd18.png)

I've done a Package uninstall and reinstall (last week) so not sure what else to do.

**Comment by alvpickmans** [comment]
Thanks for raising this issue. In previous Revit versions, the issue was due to Revit using a different version of Newtonsoft Json.Net library, which was solved by changing the package to use the same library version (https://forum.dynamobim.com/t/jsondata-package/19026/25?u=alvpickmans).

I will have a look at the new release and get back to you.

**Comment by mwo-aec** [comment]
Thank you very much

Regards,

MACHIEL ODENDAAL | Team Lead: Arch | T: 010 595 2518 | www.modena-aec.co.za<http://www.modena-aec.co.za> | disclaimer<http://www.modena.co.za/disclaimer/>
